# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessageslist',
            name='income_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='privatemessageslist',
            name='outcome_messages',
            field=models.IntegerField(default=0),
        ),
    ]
